on: 
  push:
    branches:
      - master
name: Custom Workflow
jobs:
  release-note:
    name: release-note
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release 
      run: |
        pwd
        cd hackthon
        pwd
        ./gradlew clean build
        java -jar build/libs/hackthon-0.0.1-SNAPSHOT.jar 

