
on: push
name: Custom Workflow
jobs:
  release-note:
    name: release-note
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: release 
      run: |
        pwd
        cd hackthon
        pwd
