
on: 
  push:
    branches:
      - master
name: Custom Workflow
jobs:
  release-note:
    name: release-note
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        pwd
